version: "3.7"

services:
  cg-edge-conf-api:
    image: cadugrillo/cg-edge-conf-api:2.2
    container_name: cg-edge-conf-api
    restart: always
    mem_limit: 1024m
    cpus: 0.5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - cgedge-data:/database
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /etc/network
        target: /etc/network
      - type: bind
        source: /home/edge/apps
        target: /apps
    networks:
      - cg-conf

  cg-edge-conf:
    image: cadugrillo/cg-edge-conf:2.2
    container_name: cg-edge-conf
    restart: always
    mem_limit: 1024m
    cpus: 0.5
    ports:
      - 443:443
    networks:
      - cg-conf

networks:
   cg-conf:
      name: cg-conf

volumes:
  cgedge-data:

   

