version: "3.3"
services:
  opcua-mqtt-connector:
    image: cadugrillo/opcua-mqtt-connector:1.0
    container_name: opcua-mqtt-connector
    restart: always
    volumes:
      - type: bind
        source: ./config
        target: /config
    networks:
      - cg-edge

networks:
   cg-edge:
    external: true
