version: "3.3"
services:
  mqtt-cloud-connector:
    image: cadugrillo/mqtt-cloud-connector:1.3
    container_name: mqtt-cloud-connector
    restart: always
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: ./certs
        target: /certs
    networks:
      - cg-edge

networks:
   cg-edge:
    external: true
