#OPCUA CLIENT CONFIGURATIONS
opcUaClient:
  clientId: "cg_opcua_client"
  serverAddress: "opc.tcp://172.24.50.10:4840"
  pollInterval: 10
  maxAge: 2000
#MQTT CLIENT CONFIGURATIONS
clientPub:
  clientId: "cg_opcua_publisher"
  serverAddress: "tcp://datalake:1883"
  qos: 1
  connectionTimeout: 1
  writeTimeout: 1
  keepAlive: 30
  pingTimeout: 1
  connectRetry: true
  autoConnect: true
  orderMaters: false
  userName: ""
  password: ""
  tlsConn: false
  rootCAPath: "./certs/pub/xxxxxxxx"
  clientKeyPath: "./certs/pub/xxxxxxxx"
  privateKeyPath: "./certs/pub/xxxxxxxx"
  insecureSkipVerify: true

#LOGS
logs:
  debug: true
  warning: true
  error: true
  critical: true

#MQTT TOPIC TO PUBLISH TO
topicsPub:
  topic:
    - "cg-opcua-publisher/signals"

#OPCUA NODES TO READ
nodesToRead:
  nodes:
    - 
        name: "ControlCabPowerSupply12Ok"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.ControlCabPowerSupply12Ok"
    - 
        name: "WicketGateShutdownSolEnerg"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.WicketGateShutdownSolEnerg"
    - 
        name: "RunnerBladeShutdownSolEnerg"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.RunnerBladeShutdownSolEnerg"
    - 
        name: "Spare_ENET1_DIM1_BYTE0_BIT3"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET1_DIM1_BYTE0_BIT3"
    - 
        name: "Spare_ENET1_DIM1_BYTE0_BIT4"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET1_DIM1_BYTE0_BIT4"
    - 
        name: "Spare_ENET1_DIM1_BYTE0_BIT5"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET1_DIM1_BYTE0_BIT5"
    - 
        name: "BatteryChargerFailure"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.BatteryChargerFailure"
    - 
        name: "StationServiceBreakerOpen"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.StationServiceBreakerOpen"
    - 
        name: "Spare_ENET1_DIM1_BYTE1_BIT0"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET1_DIM1_BYTE1_BIT0"
    - 
        name: "StationPhaseLossUnderV"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.StationPhaseLossUnderV"
    - 
        name: "GeneratorBreakerClosed"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GeneratorBreakerClosed"
    - 
        name: "UnitSyncSpeedRaise"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.UnitSyncSpeedRaise"
    - 
        name: "UnitSyncSpeedLower"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.UnitSyncSpeedLower"
    - 
        name: "UnitSyncVoltageRaise"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.UnitSyncVoltageRaise"
    - 
        name: "UnitSyncVoltageLower"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.UnitSyncVoltageLower"
    - 
        name: "PLCLeadSelection"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.PLCLeadSelection"
    - 
        name: "LineGroundFault51N"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.LineGroundFault51N"
    - 
        name: "LineOvercurrentFault5051"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.LineOvercurrentFault5051"
    - 
        name: "MainTransfDiff87T"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.MainTransfDiff87T"
    - 
        name: "MainBusUnderOverVoltPhA"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.MainBusUnderOverVoltPhA"
    - 
        name: "MainBusUnderOverVoltPhB"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.MainBusUnderOverVoltPhB"
    - 
        name: "MainBusUnderOverVoltPhC"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.MainBusUnderOverVoltPhC"
    - 
        name: "GenProtReversePower"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenProtReversePower"
    - 
        name: "GenTransfUndercurrent"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenTransfUndercurrent"
    - 
        name: "GenProtLossExcitation"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenProtLossExcitation"
    - 
        name: "GenProtNeutralGroundOvervolt"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenProtNeutralGroundOvervolt"
    - 
        name: "GenProtNegSeqOvercurrent"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenProtNegSeqOvercurrent"
    - 
        name: "GenProtDifferential"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenProtDifferential"
    - 
        name: "GenProtVoltCtrlTimeOvercPhA"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenProtVoltCtrlTimeOvercPhA"
    - 
        name: "GenProtVoltCtrlTimeOvercPhB"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenProtVoltCtrlTimeOvercPhB"
    - 
        name: "GenProtVoltCtrlTimeOvercPhC"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenProtVoltCtrlTimeOvercPhC"
    - 
        name: "MainBusOverUnderFreq"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.MainBusOverUnderFreq"
    - 
        name: "GatePosGreatThanSNL"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GatePosGreatThanSNL"
    - 
        name: "Spare_ENET1_DIM3_BYTE0_BIT1"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET1_DIM3_BYTE0_BIT1"
    - 
        name: "GatePosClosed"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GatePosClosed"
    - 
        name: "GatePosRaise"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GatePosRaise"
    - 
        name: "GatePosLower"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GatePosLower"
    - 
        name: "Spare_ENET1_DIM3_BYTE0_BIT5"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET1_DIM3_BYTE0_BIT5"
    - 
        name: "StopCommand"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.StopCommand"
    - 
        name: "StartCommand"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.StartCommand"
    - 
        name: "CtrlMode43CSManual"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.CtrlMode43CSManual"
    - 
        name: "CtrlMode43CS1LocalAuto"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.CtrlMode43CS1LocalAuto"
    - 
        name: "CtrlMode43CS1RemoteAuto"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.CtrlMode43CS1RemoteAuto"
    - 
        name: "GovMode43LCSLevel"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GovMode43LCSLevel"
    - 
        name: "GovMode43LCSFlow"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GovMode43LCSFlow"
    - 
        name: "AllMFSinAuto"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.AllMFSinAuto"
    - 
        name: "PLCWatchDog"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.PLCWatchDog"
    - 
        name: "ExcSystOverexcitation"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.ExcSystOverexcitation"
    - 
        name: "NonLockoutRelay94"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.NonLockoutRelay94"
    - 
        name: "LockoutRelay86E"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.LockoutRelay86E"
    - 
        name: "LockoutRelay86N"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.LockoutRelay86N"
    - 
        name: "LockoutRelay86T"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.LockoutRelay86T"
    - 
        name: "LockoutRelay86H"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.LockoutRelay86H"
    - 
        name: "StationDCOvervoltage"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.StationDCOvervoltage"
    - 
        name: "StationDCUndervoltage"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.StationDCUndervoltage"
    - 
        name: "LineBreakerPowerFailure"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.LineBreakerPowerFailure"        
    - 
        name: "UnitSpeedGreatThanShaftCreep"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.UnitSpeedGreatThanShaftCreep"
    - 
        name: "UnitSpeedGreatThanOverSpeed2"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.UnitSpeedGreatThanOverSpeed2"
    - 
        name: "UnitSpeedLessThan10pcSNL"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.UnitSpeedLessThan10pcSNL"
    - 
        name: "UnitSpeedGreatThan90pcSNL"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.UnitSpeedGreatThan90pcSNL"
    - 
        name: "UnitSpeedGreatThanOverSpeed"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.UnitSpeedGreatThanOverSpeed"
    - 
        name: "LineBreakerClosed"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.LineBreakerClosed"
    - 
        name: "ExcSystFault"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.ExcSystFault"
    - 
        name: "NormalStopButton"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.NormalStopButton"
    - 
        name: "MaintenanceSwitch"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.MaintenanceSwitch"
    - 
        name: "GenVibrationHorizontal"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenVibrationHorizontal"
    - 
        name: "ExcSystGroundFault"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.ExcSystGroundFault"
    - 
        name: "TurbVibrationNormalStop"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.TurbVibrationNormalStop"
    - 
        name: "TurbVibrationAlarm"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.TurbVibrationAlarm"
    - 
        name: "UnitMWhPulse"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.UnitMWhPulse"
    - 
        name: "Spare_ENET2_DIM5_BYTE0_BIT5"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET2_DIM5_BYTE0_BIT5"
    - 
        name: "TurbBearSealWaterFlowLow"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.TurbBearSealWaterFlowLow"
    - 
        name: "TurbGuideBearTempHigh"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.TurbGuideBearTempHigh"
    - 
        name: "PackBoxCoolWaterFlowLow"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.PackBoxCoolWaterFlowLow"
    - 
        name: "GenCoupEndGuideBearTempHigh"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenCoupEndGuideBearTempHigh"
    - 
        name: "GenLubeOilFlowLow"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenLubeOilFlowLow"
    - 
        name: "ThrustBearTempHigh"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.ThrustBearTempHigh"
    - 
        name: "Spare_ENET2_DIM5_BYTE1_BIT4"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET2_DIM5_BYTE1_BIT4"
    - 
        name: "GenOilLevelLow"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenOilLevelLow"
    - 
        name: "GenOilLevelHigh"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenOilLevelHigh"
    - 
        name: "LubeOilTankTempHigh"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.LubeOilTankTempHigh"
    - 
        name: "Spare_ENET2_DIM6_BYTE0_BIT0"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET2_DIM6_BYTE0_BIT0"
    - 
        name: "GenOutbEndGuideBearTempHigh"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GenOutbEndGuideBearTempHigh"
    - 
        name: "ShaftLocked"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.ShaftLocked"
    - 
        name: "MainTransfSuddenPressure"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.MainTransfSuddenPressure"
    - 
        name: "MainTransfTempHigh"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.MainTransfTempHigh"
    - 
        name: "MainTransfOilLevelLow"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.MainTransfOilLevelLow"
    - 
        name: "StatServiceTransfTempHigh"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.StatServiceTransfTempHigh"
    - 
        name: "HPUOilLevelLow"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.HPUOilLevelLow"
    - 
        name: "Spare_ENET2_DIM6_BYTE1_BIT0"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET2_DIM6_BYTE1_BIT0"
    - 
        name: "HPUOilPressureLowLow"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.HPUOilPressureLowLow"
    - 
        name: "HPUOilPressureLow"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.HPUOilPressureLow"
    - 
        name: "Spare_ENET2_DIM6_BYTE1_BIT3"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET2_DIM6_BYTE1_BIT3"
    - 
        name: "BrakesOn"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.BrakesOn"
    - 
        name: "CoolWaterSystPressureLow"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.CoolWaterSystPressureLow"
    - 
        name: "Fire"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Fire"
    - 
        name: "Intrusion"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Intrusion"
    - 
        name: "PlantSumpWaterLevelHigh"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.PlantSumpWaterLevelHigh"
    - 
        name: "ExcSystReady"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.ExcSystReady"
    - 
        name: "MPTOilTempHigh"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.MPTOilTempHigh"
    - 
        name: "CoolWaterSystPumpFailure"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.CoolWaterSystPumpFailure"
    - 
        name: "CoolWaterSystDiffPressureHigh"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.CoolWaterSystDiffPressureHigh"
    - 
        name: "Spare_ENET2_DIM7_BYTE0_BIT5"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET2_DIM7_BYTE0_BIT5"
    - 
        name: "VoltageImbalance"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.VoltageImbalance"
    - 
        name: "GNDFault"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.GNDFault"
    - 
        name: "BatteryDisconnectPosition"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.BatteryDisconnectPosition"
    - 
        name: "B52G2"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.B52G2"
