#OPCUA CLIENT CONFIGURATIONS
opcUaClient:
  clientId: "cg_opcua_client"
  serverAddress: "opc.tcp://172.24.50.10:4840"
  pollInterval: 10
  maxAge: 2000
#MQTT CLIENT CONFIGURATIONS
clientPub:
  clientId: "cg_opcua_publisher"
  serverAddress: "tcp://datalake:1883"
  qos: 1
  connectionTimeout: 1
  writeTimeout: 1
  keepAlive: 30
  pingTimeout: 1
  connectRetry: true
  autoConnect: true
  orderMaters: false
  userName: ""
  password: ""
  tlsConn: false
  rootCAPath: "./certs/pub/xxxxxxxx"
  clientKeyPath: "./certs/pub/xxxxxxxx"
  privateKeyPath: "./certs/pub/xxxxxxxx"
  insecureSkipVerify: true

#LOGS
logs:
  debug: true
  warning: true
  error: true
  critical: true

#MQTT TOPIC TO PUBLISH TO
topicsPub:
  topic:
    - "cg-opcua-publisher/signals"

#OPCUA NODES TO READ
nodesToRead:
