#OPCUA CLIENT CONFIGURATIONS
opcUaClient:
  clientId: "cg_opcua_client"
  serverAddress: "opc.tcp://172.24.50.10:4840"
  pollInterval: 10
  maxAge: 2000
#MQTT CLIENT CONFIGURATIONS
clientPub:
  clientId: "cg_opcua_publisher"
  serverAddress: "tcp://datalake:1883"
  qos: 1
  connectionTimeout: 1
  writeTimeout: 1
  keepAlive: 30
  pingTimeout: 1
  connectRetry: true
  autoConnect: true
  orderMaters: false
  userName: ""
  password: ""
  tlsConn: false
  rootCAPath: "./certs/pub/xxxxxxxx"
  clientKeyPath: "./certs/pub/xxxxxxxx"
  privateKeyPath: "./certs/pub/xxxxxxxx"
  insecureSkipVerify: true

#LOGS
logs:
  debug: true
  warning: true
  error: true
  critical: true

#MQTT TOPIC TO PUBLISH TO
topicsPub:
  topic:
    - "cg-opcua-publisher/signals"

#OPCUA NODES TO READ
nodesToRead:
  nodes:
    - 
        name: "ControlCabPowerSupply12Ok"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.ControlCabPowerSupply12Ok"
    - 
        name: "WicketGateShutdownSolEnerg"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.WicketGateShutdownSolEnerg"
    - 
        name: "RunnerBladeShutdownSolEnerg"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.RunnerBladeShutdownSolEnerg"
    - 
        name: "Spare_ENET1_DIM1_BYTE0_BIT3"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET1_DIM1_BYTE0_BIT3"
    - 
        name: "Spare_ENET1_DIM1_BYTE0_BIT4"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET1_DIM1_BYTE0_BIT4"
    - 
        name: "Spare_ENET1_DIM1_BYTE0_BIT5"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET1_DIM1_BYTE0_BIT5"
    - 
        name: "BatteryChargerFailure"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.BatteryChargerFailure"
    - 
        name: "StationServiceBreakerOpen"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.StationServiceBreakerOpen"
    - 
        name: "Spare_ENET1_DIM1_BYTE1_BIT0"
        nodeID: "ns=4;s=|var|CODESYS Control for emPC-A-iMX6 SL.Application.DB1.Spare_ENET1_DIM1_BYTE1_BIT0"
